name: Debug game preview

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate-gamedata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate gamedata
        run: |
          php conversor-csv/convert.php

          cat ./projeto/Scripts/Data/GameData.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gamedata
          path: ./projeto/Scripts/Data/GameData.json

  deploy-to-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: generate-gamedata
    container:
      image: nawarian/godot:4.3-stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download generated gamedata
        uses: actions/download-artifact@v4
        with:
          name: gamedata
          path: ./projeto/Scripts/Data/

      - name: Build web
        env:
          HOME: /root
        run: |
          mkdir build/
          godot --display-driver headless --verbose --export-debug "Web" $(pwd)/build/index.html

          mv vendor/coi.min.js build/coi.min.js
          sed -i '3 i <script src="coi.min.js"></script>' build/index.html
        working-directory: ./projeto

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: projeto/build/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
